### ISSUE TITLE
Custom elements not supported

### ISSUE THREAD

**Issue by thomaswilburn** [jgm/CommonMark#239]
We use CommonMark as our document parser at the Seattle Times on some special projects, and it has problems recognizing our custom elements when we try to insert them into the document as HTML. For example, this is not recognized:

```
<responsive-frame src="example.com"></responsive-frame>
```

A workaround is that we can wrap it in a known HTML element, such as a div, and that will be recognized:

```
<div>
  <responsive-frame src="example.com"></responsive-frame>
</div>
```

But this is ugly, and it goes against the point of our custom elements, which is to be more usable for non-technical producers. Can we get the HTML parser to recognize these valid elements as HTML?

**Comment by jgm** [comment]
@thomaswilburn - Note the following.

```
<responsive-frame src="example.com">
</responsive-frame>
```
will be treated as a raw HTML block, and reproduced verbatim.

```
<responsive-frame src="example.com"></responsive-frame>
```
will be treated as a paragraph with inline HTML tags, and reproduced with `<p>...</p>` surrounding it.

See the new spec for HTML blocks (still in master, not published) for further details on how this works.

**Comment by thomaswilburn** [comment]
Awesome, thanks John.
