### ISSUE TITLE
Flanking mismatch in spec?

### ISSUE THREAD

**Issue by elliottslaughter** [jgm/CommonMark#257]
In the spec 0.14, where the rules define emphasis based on delimiter runs and flanking, I believe the sides are mismatched in rules 3 and 4 (closing emphasis with * and _):

  * https://github.com/jgm/CommonMark/blob/master/spec.txt#L4541
  * https://github.com/jgm/CommonMark/blob/master/spec.txt#L4545

If I am not mistaken, these should be part of a right-flanking delimiter run, not a left flanking one.

**Comment by jgm** [comment]
I see some other errors too.  That's what I get for changing terminology
from 'right-facing' to 'right-flanking' (which of course means the
opposite).

+++ Elliott Slaughter [Dec 31 14 15:45 ]:

**Comment by jgm** [comment]
Thanks!

+++ Elliott Slaughter [Dec 31 14 15:45 ]:
