### ISSUE TITLE
[] doesn't necessarily bind more tightly than **

### ISSUE THREAD

**Issue by jmendeth** [jgm/CommonMark#258]
In older versions of the spec, a `[]` was said to bind always, even if it was not a valid link or image.
Therefore, `*foo [bar* bar]` rendered to `*foo [bar* baz]` rather than `<em>foo [bar</em> baz]`.

With the current version, however, I couldn't find any reference of that, so it'd be nice to add an example like that to the spec, in order to make old parsers fail.

**Comment by jmendeth** [comment]
(Accidentally submitted early, corrected now)

**Comment by jgm** [comment]
Compare:

    *foo [bar* bar]()

Links still bind more tightly than emphasis.  However, brackets that aren't links, as in your example, do not.  You're right that a couple more examples of this kind could be helpful.

**Comment by jmendeth** [comment]
My parser had been targeting the new spec for months, but had this old behaviour, and I didn't notice until today.
