### ISSUE TITLE
Indented code blocks: minor rewording about interior blank lines and attributes

### ISSUE THREAD

**Issue by hoylen** [jgm/CommonMark#262]
[Section 4.4 of version 0.15](http://spec.commonmark.org/0.15/#indented-code-blocks) starts off by stating:

> An indented code block is composed of one or more indented chunks separated by blank lines. An indented chunk is a sequence of non-blank lines, each indented four or more spaces.

But this is not entirely true, since later on a distinction is made between blank lines that separate indented chunks and _interior_ blank lines which don't.

The term "blank line" is formally defined, but "interior blank line" is not.

It would be better if this was worded to be completely true. For example, saying "An indented code block is composed of one or more indented chunks separated by blank lines containing less than 4 spaces. An indented chunk is a sequence of lines each indented by four or more spaces."

The text also says:

> An indented code block has no attributes.

Which is confusing to a new reader, since the concept of "attributes" has not been introduced at this point of the specification.

Actually, attributes don't belong in the CommonMark data model, but is a feature of HTML output (one of the, but not the only, outputs/uses of CommonMark). A more correct statement (though I would still say it is unnecessary) is to say, "The _indented code block_ generates a HTML `code` element that has no attributes."

**Comment by hoylen** [comment]
Upon further thought, _indented code blocks_ and _fenced code blocks_ appear to be two syntaxes to represent the abstract CommonMark concept of a "code block". The only semantic distinction is that an _indented code block_ has no syntactic mechanism to specify an _info string_.

So instead of saying, "An indented code block has no attributes." It should really say, "An indented code block has no info string." It might help to introduce the concept of an abstract code block as mandatory content (possibly empty) plus an optional non-empty info string, and _indented code blocks_ and _fenced code blocks_ are two syntactic ways of representing them in the CommonMark syntax. And info strings are never empty strings.

**Comment by jgm** [comment]
+++ Hoylen Sue [Jan 02 15 17:56 ]:
>[Section 4.4 of version 0.15](http://spec.commonmark.org/0.15/#indented-code-blocks) starts off by stating:
>
>> An indented code block is composed of one or more indented chunks separated by blank lines. An indented chunk is a sequence of non-blank lines, each indented four or more spaces.
>
>But this is not entirely true, since later on a distinction is made between blank lines that separate indented chunks and _interior_ blank lines which don't.

I think you misunderstand here.  By "interior blank lines" I just mean
blank lines separating two indented chunks in the same code block. (I
only see one occurence of this term, at l. 1063.)

**Comment by jgm** [comment]
+++ Hoylen Sue [Jan 02 15 18:24 ]:
>Upon further thought, _indented code blocks_ and _fenced code blocks_ appear to be two syntaxes to represent the abstract CommonMark concept of a "code block". The only semantic distinction is that an _indented code block_ has no syntactic mechanism to specify an _info string_.
>
>So instead of saying, "An indented code block has no attributes." It should really say, "An indented code block has no info string." It might help to introduce the concept of an abstract code block as mandatory content (possibly empty) plus an optional non-empty info string, and _indented code blocks_ and _fenced code blocks_ are two syntactic ways of representing them in the CommonMark syntax. And info strings are never empty strings.

Yes, I agree that would be better.

**Comment by hoylen** [comment]
> I think you misunderstand here.  By "interior blank lines" I just mean blank lines separating two indented chunks in the same code block.

Yes. My concern was that "interior blank lines" also satisfy the definition of "blank lines" (they just contain 4 or more spaces). Blank lines which are not interior blank lines contain 3 or less spaces.

The initial sentence that says, "_An indented code block is composed of one or more indented chunks separated by blank lines_" is not entirely true. A true (but convoluted) statement would have been, "_An indented code block is composed of one or more indented chunks separated by `blank lines which are not interior blank lines'_".

**Comment by jgm** [comment]
+++ Hoylen Sue [Jan 05 15 21:17 ]:
>> I think you misunderstand here.  By "interior blank lines" I just mean blank lines separating two indented chunks in the same code block.
>
>Yes. My concern was that "interior blank lines" also satisfy the definition of "blank lines" (they just contain 4 or more spaces). Blank lines which are not interior blank lines contain 3 or less spaces.

No, interior blank lines can contain any number of spaces.  All
"interior" means is that they are inside the code block.

>The initial sentence that says, "_An indented code block is composed of one or more indented chunks separated by blank lines_" is not entirely true. A true (but convoluted) statement would have been, "_An indented code block is composed of one or more indented chunks separated by `blank lines which are not interior blank lines'_".

I think there's some confusion here.  By "interior blank line," I just
mean a blank line in the interior of a code block -- i.e. a blank line
that occurs between two indented chunks.  "Interior" has nothing to do
with the number of spaces in the line.  Blank lines are treated the
same, no matter how many spaces they contain.

**Comment by hoylen** [comment]
Thanks for clarifying that.

For some reason, I incorrectly thought that it was trying to allow multiple _indented code blocks_ to appear with no other blocks between them. That is, I incorrectly thought it was trying to do something like:

    ␣␣␣␣foo
    ␣␣
    ␣␣␣␣bar
    ␣␣␣␣
    ␣␣␣␣baz

To get:

    <code_block>foo
    </code_block>
    <code_block>bar
    
    baz
    </code_block>

But now I see that is not possible, since they will always collapse together to become one big code block:

    <code_block>foo
    
    bar
    
    baz
    </code_block>

If someone wants two code blocks, they will have to use the _fenced code block_ syntax instead of the _indented code block_ syntax. No problem there.

But it was the introduction of the concept of an **indented chunk** that led me to that misunderstanding. Now understanding the way it really works, I don't see why _indented chunks_ need to be defined or mentioned at all. Certainly `cmark` doesn't generate:

    <code_block>
      <indented_chunk>foo
      </indented_chunk>
      <indented_chunk>bar
      </indented_chunk>
      <indented_chunk>baz
      </indented_chunk>
    </code_block>

Maybe the term **indented chunk** can be dropped? It is only ever mentioned in [Section 4.4](http://spec.commonmark.org/0.15/#indented-code-blocks).

**Comment by jgm** [comment]
The reason for using the concept of "indented chunks" is
that we can't say:

- an indented code block is a sequence of indented lines

since the blank lines don't need to have indents, and we
can't say:

- an indented code block is a sequence of indented of blank
  lines,

since this would include the final and initial blank lines.

Maybe there's an alternative that would be better, but
I haven't thought of one.

**Comment by hoylen** [comment]
I think your second wording works, after adding in the exception:

> An _indented code block_ is a sequence of indented lines and blank lines, but excludes any initial and final blank lines. An indented code block must contain at least one indented line. The blank lines can be indented or not.

It tells it like it is. But I'm happy for _indented chunk_ to remain - there are more important things to work on.
