### ISSUE TITLE
[cdata re] halt with CPU 100% on some html

### ISSUE THREAD

**Issue by puzrin** [jgm/CommonMark#267]
Put this into dingus:

```
foo <![CDATA[ xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ]>
```

Similar to #263, found by @rlidwka .

Seems we should seriously revisit all attempts to parse HTML with regexp.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/commit/89c8620157d6e38f9872811620d25138fc9d1b0d

`/<!\[CDATA\[[\s\S]*?\]\]>/` - this one works. Should satisfy HTML5 spec conditions. I don't know what were cutted conditions for.

**Comment by jgm** [comment]
A CDATA section cannot contain the string `]]>`.  The complex regex in the source was meant to rule that out.  Your regex should work fine -- it uses non-greedy matching to the same effect.  The one I used was designed for cmark and re2c, which doesn't have a non-greedy matching operator.  Best solution is probably to use your regex for the js and the original one in cmark.

**Comment by puzrin** [comment]
Thanks for explanation. I'm not very strong in regexps and not familiar at all with implementation differences. Didn't know that re2c does not support non-gready matches.

Please, take a look if other JS regexps are ddos-able. @rlidwka did not found anything else, but it worth to duplucate this check for sure.

**Comment by rlidwka** [comment]
Just for the reference:

https://en.wikipedia.org/wiki/ReDoS
https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

I didn't find anything obvious, but a few other regexps are kinda fishy, worth checking out.
