### ISSUE TITLE
Blank lines in link titles

### ISSUE THREAD

**Issue by EinfachToll** [jgm/CommonMark#271]
According to the spec, newlines in link titles are allowed. However, the current implementation allows newlines in the link title of a link reference definition only if they don't form a blank line. IMO, that makes sense, but isn't covered by the spec, as far as I can see.

**Comment by jgm** [comment]
See http://spec.commonmark.org/0.15/#precedence -
indicators of block structure always take precedence over
indicators of inline structure.  So if you have

    [link](url "title

    with blank line")

the indicator of block structure (the blank line) takes
precedence, dividing this into two paragraphs, whose raw
contents are only then parsed as inlines.

Does that clear things up?

+++ EinfachToll [Jan 06 15 05:13 ]:

**Comment by EinfachToll** [comment]
Not, that does not clear things up. Sorry, I should have emphasized more that I'm not talking about inline links, but about link reference definitions which are block structures. And as far as I can see there is no rule that forbids empty lines in link reference definitions.

**Comment by jgm** [comment]
OK, thanks, reopening.  We can clarify that.
