### ISSUE TITLE
Missing paragraph <p> tag in loose list

### ISSUE THREAD

**Issue by GeniusWiki** [jgm/CommonMark#285]
1.  ```
        code
        ```

        last line - end


In commonmark.js, the last line is not inside a `<p>` tag. Base on spec. This is could be a loose list because a blank line between code block and last line.

If removed this order list, the last line is inside a `<p>` even without that blank line.

**Comment by jgm** [comment]
The problem is that the fenced code block is finalized before we know whether the next line is blank, so the `_lastLineBlank` property doesn't get set.  The proper fix needs some thought.

**Comment by jgm** [comment]
We also need a test case like this in the spec.
