### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by bwasty** [jgm/CommonMark#288]
It would be nice if CommonMark could simply be installed via `bower install commonmark`. There is already a discussion about it: http://talk.commonmark.org/t/bower-npm-publishing-of-js-implementation/70/7

**Comment by colinodell** [comment]
+1

**Comment by jgm** [comment]
It would also make sense to separate out the JS project into its own repository.

**Comment by jgm** [comment]
I have split off the repository and added a `bower.json`, but I think I should wait for the 0.17 release to register it.

**Comment by jgm** [comment]
The bower package has been registered.
