### ISSUE TITLE
Source position attribute in XML schema

### ISSUE THREAD

**Issue by Knagis** [jgm/CommonMark#298]
Currently the XML schema does not provide details on how the `sourcepos` attribute should be formatted. It would be nice if the `.dtd` file included at least a comment describing the value format.

But there is another problem as well - in my .NET implementation I have deprecated the `start_line` / `start_column` properties and instead keep track of the exact location of the element start and end (for both blocks and inlines). This was a request from multiple creators of editor applications - for them the original properties does not suffice.

It would be nice if the schema included guidance on what to do with source position attribute value in such case - I imagine there could be other implementations as well that would choose this type of source position tracking instead of line/column.

Maybe the `sourcepos` attribute could be described to contain two scenarios:
* `sourcepos="1:1-1:10"` - if line tracking is used
* `sourcepos="1-10"` - if character tracking is used.

Of course, there is one more question - do the positions (in either case) point to bytes or unicode codepoints or characters (by this distinction I mean cases like .NET and JavaScript where the language uses UCS-2 and surrogate pairs that are separated in two characters). It could be that this is left undefined and the implementation would most probably choose the value that makes sense in that particular language/framework.

**Comment by jgm** [comment]
+++ Kārlis Gaņģis [Feb 01 15 11:03 ]:
>Currently the XML schema does not provide details on how the `sourcepos` attribute should be formatted. It would be nice if the `.dtd` file included at least a comment describing the value format.

Agreed.  Currently it's [startline]:[startcolumn]-[endline]:[endcolumn],
but I'm open to other possibilities.  (This is much more compact than
separate attributes, but on the other hand it makes it harder to get at
the attributes.)

>But there is another problem as well - in my .NET implementation I have deprecated the `start_line` / `start_column` properties and instead keep track of the exact location of the element start and end (for both blocks and inlines). This was a request from multiple creators of editor applications - for them the original properties does not suffice.

The current cmark and commonmark.js implementations do now track start and
end position for block elements.  But not inline elements -- the way
they are parsed, tracking this information would require additional
complications.

>Of course, there is one more question - do the positions (in either case) point to bytes or unicode codepoints or characters (by this distinction I mean cases like .NET and JavaScript where the language uses UCS-2 and surrogate pairs that are separated in two characters). It could be that this is left undefined and the implementation would most probably choose the value that makes sense in that particular language/framework.

I'm afraid I didn't think of this.  cmark does bytes and commonmark.js
does code points.  Maybe leaving it implementation-dependent does make
sense, though.
