### ISSUE TITLE
Backslash for hard line break

### ISSUE THREAD

**Issue by adius** [jgm/CommonMark#299]
I just wanted to mention that I think the backslash hard line break is a very unfortunate choice.
In several programming languages e.g. Javascript and bash the backslash can be used exactly for the opposite purpose: It can escape the following newline character in order to ignore the following line break. Couldn't you come up with something different?

**Comment by jgm** [comment]
+++ Adrian Sieber [Feb 04 15 01:31 ]:
>I just wanted to mention that I think the backslash hard line break is a very unfortunate choice.
>In several programming languages e.g. Javascript and bash the backslash can be used exactly for the opposite purpose: It can escape the following newline character in order to ignore the following line break. Couldn't you come up with something different?

This kind of open-ended discussion comment should go on http://talk.commonmark.org rather than on the bug tracker.  (If you search, you'll find some relevant discussions there.)
