### ISSUE TITLE
The purpose of \v

### ISSUE THREAD

**Issue by opennota** [jgm/CommonMark#300]
What's the purpose of not listing `\v` ([LINE TABULATION](http://www.fileformat.info/info/unicode/char/000B/index.htm)) among the unicode whitespace characters?

**Comment by opennota** [comment]
[Java](https://gist.github.com/opennota/77e8198325adcac1b9eb) thinks it's a whitespace. [Go](http://play.golang.org/p/TAcbLwo57E) too.

**Comment by jgm** [comment]
We could add it.  I don't see any reason not to.

+++ opennota [Feb 11 15 14:10 ]:
>   What's the purpose of not listing \v [1](LINE TABULATION) among the
>   unicode whitespace characters?

**Comment by opennota** [comment]
@jgm That would be nice.
