### ISSUE TITLE
right/left-flanking delimiter run definitions: need clarification

### ISSUE THREAD

**Issue by opennota** [jgm/CommonMark#302]
An excerpt from the spec:

> A **delimiter run** is either a sequence of one or more `*` characters that is not preceded or followed by a `*` character, or a sequence of one or more `_` characters that is not preceded or followed by a `_` character.
> 
> A **right-flanking delimiter run** is a delimiter run that is (a) not preceded by unicode whitespace, and (b) either not preceded by a punctuation character, or followed by unicode whitespace or a punctuation character.
> 
> - left-flanking **but not right-flanking**:
> 
> ```
> ***abc
> _abc
> ```

How come that `***` and `_` here aren't right-flanking? They are (a) not preceded by unicode whitespace (they aren't preceded by any character whatsoever) and, by the same logic, they are (b) not preceded by a punctuation character; all that effectively makes them the right-flanking delimiter runs, according to the spec.

**Comment by jgm** [comment]
+++ opennota [Feb 17 15 03:34 ]:
>An excerpt from the spec:
>
>> A **delimiter run** is either a sequence of one or more `*` characters that is not preceded or followed by a `*` character, or a sequence of one or more `_` characters that is not preceded or followed by a `_` character.
>>
>> A **right-flanking delimiter run** is a delimiter run that is (a) not preceded by unicode whitespace, and (b) either not preceded by a punctuation character, or followed by unicode whitespace or a punctuation character.
>>
>> - left-flanking **but not right-flanking**:
>>
>> ```
>> ***abc
>> _abc
>> ```
>
>How come that `***` and `_` here aren't right-flanking? They are (a) not preceded by unicode whitespace (they aren't preceded by any character whatsoever) and, by the same logic, they are (b) not preceded by a punctuation character; all that effectively makes them the right-flanking delimiter runs, according to the spec.

Good.  The code treats the beginning and end of the line as whitespace characters, but this isn't clear in the spec.  Want to open an issue on the github tracker to clarify this?

**Comment by jgm** [comment]
Sorry...this *is* on the tracker (I'd thought I was getting the email through the talk page).
Thanks.
