### ISSUE TITLE
Precedence of heading and code.

### ISSUE THREAD

**Issue by dikmax** [jgm/CommonMark#306]
I found this while testing compatibility of my parser with official js implementation.

Test:

    ```
    -

Parsed as fenced code, while my implementation as heading.

Shouldn't this ambiguity be cleared in spec?

**Comment by jgm** [comment]
I think this was already settled in the spec:

> A setext header consists of a line of text, containing at least one non-space character, with no more than 3 spaces indentation, followed by a setext header underline. **The line of text must be one that, were it not followed by the setext header underline, would be interpreted as part of a paragraph:** it cannot be a code block, header, blockquote, horizontal rule, or list. [emphasis added]

But I've rewritten this to make it clearer:

> A setext header consists of a line of text, containing at least one non-space character, with no more than 3 spaces indentation, followed by a setext header underline. The line of text must be one that, were it not followed by the setext header underline, would be interpreted as part of a paragraph: it cannot be interpretable as a code fence, ATX header, block quote, horizontal rule, list item, or HTML block.
