### ISSUE TITLE
Left-flanking / right-flanking (again?)

### ISSUE THREAD

**Issue by jmendeth** [jgm/CommonMark#310]
I'm kinda pissed off. I implemented emphasis according to the spec, and now my parser is rendering `_foo_` as `<p>_foo_</p>`. I verified that, according to the rules in 0.17, the two delimiter runs are both right- and left- flanking. So my parser is actually right!

So I go checkout 0.18 and I find the definition has changed a bit, it's now even more permissive. So `_foo_` is still `<p>_foo_</p>`. I also checked master before submitting this.

Then I find in #302 (and in CMark code) that the code treats start of line and end of line as whitespace, and @jgm attempted to correct the spec. However `_foo_` is still having both left- and right- flanking delimiter runs.

I suppose this would be fixed by changing:

~~~ diff
 A [left-flanking delimiter run](@left-flanking-delimiter-run) is
-a [delimiter run] that is (a) not followed by [unicode whitespace],
+a [delimiter run] that is (a) not followed by [unicode whitespace] or end of line,
 and (b) either not followed by a [punctuation character], or
 preceded by [unicode whitespace] or a [punctuation character] or
 the beginning of a line.

 A [right-flanking delimiter run](@right-flanking-delimiter-run) is
-a [delimiter run] that is (a) not preceded by [unicode whitespace],
+a [delimiter run] that is (a) not preceded by [unicode whitespace] or end of line,
 and (b) either not preceded by a [punctuation character], or
 followed by [unicode whitespace] or a [punctuation character] or
 the end of a line.
~~~

But those two definitions are getting very messy IMO...

**Comment by jgm** [comment]
+++ Xavier Mendez [Mar 10 15 13:59 ]:
>   I'm kinda pissed off. I implemented emphasis according to the spec, and
>   now my parser is rendering _foo_ as <p>_foo_</p>. I verified that,
>   according to the rules in 0.17, the two delimiter runs are both right-
>   and left- flanking. So my parser is actually right!
>
>   So I go checkout 0.18 and I find the definition has changed a bit, it's
>   now even more permissive. So _foo_ is still <p>_foo_</p>. I also
>   checked master before submitting this.
>
>   Then I find in [1]#302 (and in CMark code) that the code treats start
>   of line and end of line as whitespace, and [2]@jgm attempted to correct
>   the spec. However _foo_ is still having both left- and right- flanking
>   delimiter runs.

My original instinct in adjusting the spec was just to add:
"for these purposes the beginning and end of the line count
as whitespace."  I then decided to make it more explicit, but
as you've pointed out, I didn't get it quite right.

For the sake of simplicity, would it be better to say the
following?

> A [left-flanking delimiter run](@left-flanking-delimiter-run) is
>-a [delimiter run] that is (a) not followed by [unicode whitespace],
> and (b) either not followed by a [punctuation character], or
> preceded by [unicode whitespace] or a [punctuation character].
> For these purposes the beginning and end of line count as
> [unicode whitespace].

**Comment by jmendeth** [comment]
Yeah.

**Comment by jgm** [comment]
See https://github.com/jgm/commonmark.js/issues/12 for a related issue.
