### ISSUE TITLE
Trailing period prevents links within emphasis

### ISSUE THREAD

**Issue by cliss** [jgm/CommonMark#317]
Re-opened here from [markdown-it #94](https://github.com/markdown-it/markdown-it/issues/94). As was [pointed out to me](https://github.com/markdown-it/markdown-it/issues/94#issuecomment-94814674) by @rlidwka, this seems to be broken in the dingus as well, despite what I initially thought below. As per @rlidwka, it appears the trailing period is causing the confusion.

<hr />

I'm seeing a bug wherein a link within an emphasis/bold block is not showing as `strong`.

Example:

```
> md.render('This is a __[test of a link in bold](http://www.github.com/)__.')
'<p>This is a __<a href="http://www.github.com/">test of a link in bold</a>__.</p>\n'
```

I would have expected:

```
'<p>This is a <strong><a href="http://www.github.com/">test of a link in bold</a></strong>.</p>'
```

You'll note that this works as expected when the link is not included:

```
> md.render('This is a __test of bold__.')
'<p>This is a <strong>test of bold</strong>.</p>\n'
```

This seems to work as I expected on the [Commonmark Dingus](http://spec.commonmark.org/dingus/?text=This%20is%20a%20__%5Btest%20of%20a%20link%5D(http%3A%2F%2Fwww.github.com)%20in%20bold__.%0A%0AThis%20is%20a%20__test%20of%20bold__.).

If this user error, my utmost apologies; please let me know what I'm doing wrong!

**Comment by colinodell** [comment]
I ran those strings through Babelmark2 and am seeing [similar results](http://johnmacfarlane.net/babelmark2/?normalize=1&text=This+is+a+__%5Btest+of+a+link+in+bold%5D(http%3A%2F%2Fwww.github.com%2F)__.%0A%0AThis+is+a+__%5Btest+of+a+link%5D(http%3A%2F%2Fwww.github.com)+in+bold__.%0A%0AThis+is+a+__test+of+bold__.).

**Comment by colinodell** [comment]
Actually, [it looks the issue occurs](http://johnmacfarlane.net/babelmark2/?normalize=1&text=This+is+a+__%5Btest%5D__.%0A%0AThis+is+a+__%5Btest%5D__!%0A%0AThis+is+a+__%5Btest%5D__%3F) regardless of which [punctuation character](http://spec.commonmark.org/0.18/#punctuation-character) appears at the end.

Could this be a bug where the ending `__` isn't being identified as a [right-flanking delimiter run](http://spec.commonmark.org/0.18/#right-flanking-delimiter-run)?

**Comment by jgm** [comment]
See jgm/commonmark.js#12 - this is the same issue, I believe, and a solution is sketched out there.  I mean to give this some further thought, but will probably implement what is described there.  Comments welcome.

**Comment by puzrin** [comment]
I think, that's implementation bug in markdown-it: https://github.com/markdown-it/markdown-it/issues/97

Spec looks good for me with last commits.

**Comment by puzrin** [comment]
Tests missed. Example with link needed in spec.
