### ISSUE TITLE
Don’t convert tabs to spaces

### ISSUE THREAD

**Issue by flying-sheep** [jgm/CommonMark#318]
tab width can be configured using CSS [tab-size](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size), and are syntactically relevant in (at least) makefiles, python, and genie, all of which will be destroyed by the conversion.

so the practical solution is to change the spec to something like

> Tabs that are used to indent markdown blocks are converted to 4 spaces each. tabs in code blocks (after dedenting) are retained

**Comment by cebe** [comment]
:+1:

**Comment by technocrat** [comment]
PEP 8

Spaces are the preferred indentation method.

Tabs should be used solely to remain consistent with code that is already
indented with tabs.

Python 3 disallows mixing the use of tabs and spaces for indentation.

Python 2 code indented with a mixture of tabs and spaces should be
converted to using spaces exclusively.

When invoking the Python 2 command line interpreter with the -t option, it
issues warnings about code that illegally mixes tabs and spaces. When using
-tt these warnings become errors. These options are highly recommended!

**Comment by jgm** [comment]
@flying-sheep - I'm going to close this here, since this tracker is for clear bugs that are actionable, not for revisions to the spec that need discussion.  You should bring it up as a topic on http://talk.commonmark.org.

**Comment by flying-sheep** [comment]
what does this have to do with python? i just mentioned python as *one of* the examples where tabs make a syntactical difference, i.e. where the spec’s replacement will destroy working code. i didn’t say that it would be good style in the case of python.

makefiles though… observe:

```Makefile
all:
	echo 'observe how copying this code will miserably fail since the syntactically relavant tab is missing'
```

**Comment by technocrat** [comment]
Python code blocks embedded in CM shouldn't have spaces converted to 
tabs in the hope that the resulting HTML will be rendered with CSS to 
convert them back into spaces. Nor should makefiles have their tabs 
converted to spaces. Seems that the sensible thing is to respect the 
author's intent and pass through the code block without changing the 
choice of tabs vs. spaces.

Philipp A. wrote:

**Comment by flying-sheep** [comment]
> converted to tabs

what.

**Comment by technocrat** [comment]
I got things off track, sorry. Yes, after indenting code block with space,
retain original whitespace, whether tabs or spaces

**Comment by flying-sheep** [comment]
Exactly. I also explain it in the talk topic linked above: All whitespace that’s used for markdown (e.g. to determine list level) is normalized. all superfluous whitespace is retained.

e.g. (with “`———→`” meaning a tab character):

```md
1. First level list

———→* 2nd level list

	* 2nd level list

		Text in 2nd level list

		```
		Code block inside 2nd level list
		———→tab-indented line inside of codeblock
		    space-indented line inside of codeblock
		Last line of codeblock
		```
```

is converted to

>1. First level list
>
>	* 2nd level list
>
>	* 2nd level list
>
>		Text in 2nd level list
>
>		```
>		Code block inside 2nd level list
>		———→tab-indented line inside of codeblock
>		    space-indented line inside of codeblock
>		Last line of codeblock
>		```
