### ISSUE TITLE
Forbid generating NULL using decimal entity

### ISSUE THREAD

**Issue by raphlinus** [jgm/CommonMark#323]
The spec should disallow generating null using `&#0;`, as doing so would be inconsistent with the security rationale listed in section 2.1 "Characters and Lines". There are three plausible renderings of this sequence on input: the empty string,` U+FFFD`, or rendering the input literally (escaping the `&`). The cmark reference implementation currently does the latter. In any case, I would prefer it if the output was actually specified (unlike the current language in 2.1).

**Comment by nwellnhof** [comment]
+1 for specifiying the output. See https://github.com/jgm/CommonMark/issues/327.

I chose to use U+FFFD as replacement for entities in the C library, matching the handling of NULL characters (U+0000). I think this is the most consistent solution and the best way to make clear what happened.
