### ISSUE TITLE
Space on end of first line of HTML block

### ISSUE THREAD

**Issue by BigBadaboom** [jgm/CommonMark#324]
Notwithstanding the discussion in #177, there remains a bug in the reference implementation.  The commonmark.js parser generates different results depending on whether the opening tag ends with a space or not.

Compare:

http://spec.commonmark.org/dingus/?text=%3Cdiv%20%0A%20class%0Afoo%0A

vs

http://spec.commonmark.org/dingus/?text=%3Cdiv%0A%20class%0Afoo%0A

I don't think it makes any sense that these two samples should be interpreted differently.

**Comment by jgm** [comment]
+++ BigBadaboom [May 12 15 22:33 ]:

>I don't think it makes any sense that these two samples should be interpreted differently.

Agreed.

**Comment by jgm** [comment]
Fixed by jgm/commonmark 6afa4762a784a0ff5a727cac49cce8478243e21b
