### ISSUE TITLE
Escaped backslash at end of link label

### ISSUE THREAD

**Issue by BigBadaboom** [jgm/CommonMark#325]
If I am reading the spec right, the following sample should be a valid link label shouldn't it?

````
[bar\\]: /url "title"

[bar\\]
````

http://spec.commonmark.org/dingus/?text=%5Bbar%5C%5C%5D%3A%20%2Furl%20%22title%22%0A%0A%5Bbar%5C%5C%5D%0A

However commonmark.js is not recognising it as such, and is instead generating a paragraph.

**Comment by jgm** [comment]
Yes, this is a bug.  (cmark does the right thing here.)
Thanks for reporting.

**Comment by jgm** [comment]
Could you open an issue on jgm/commonmark.js instead of here?

**Comment by BigBadaboom** [comment]
Done.

Sorry, I didn't realise there was a separate repo.

**Comment by jgm** [comment]
Re-opening.  This has been fixed in commonmark.js, but it would be good to have a test case for this in the spec.
