### ISSUE TITLE
Tab expansion (sec 2.2) should specify that it is applied early

### ISSUE THREAD

**Issue by danstowell** [jgm/CommonMark#330]
I presume that the tab expansion given in sec 2.2 is applied early on in processing. I'm pretty sure that order-of-execution of markdown processing rules would change the effect (eg sec 4.4/4.5 on code blocks). But I don't think the wording of sec 2.2 is explicit about that. I'd suggest a change such as altering

> Tabs in lines are expanded to spaces, with a tab stop of 4 characters:

to

> Tab characters in input are immediately expanded to spaces, with a tab stop of 4 characters:

**Comment by colinodell** [comment]
Perhaps you could also/instead move or rename section 2.2 into a new section called "Pre-processing" (or something to that effect)?
