### ISSUE TITLE
Confusion over code tags.

### ISSUE THREAD

**Issue by Aaronepower** [jgm/CommonMark#333]
The following examples use `<p><code></code></p>` where the rest use `<pre><code></code></pre>`. Is this the actual behavior or just typos?

[#Example-90](http://spec.commonmark.org/0.20/#example-90)
[#Example-97](http://spec.commonmark.org/0.20/#example-97)
[#Example-230](http://spec.commonmark.org/0.20/#example-230)
[#Example-236](http://spec.commonmark.org/0.20/#example-236)
[#Example-254](http://spec.commonmark.org/0.20/#example-254)
[#Example-256](http://spec.commonmark.org/0.20/#example-256)
[#Example-257](http://spec.commonmark.org/0.20/#example-257)
[#Example-258](http://spec.commonmark.org/0.20/#example-258)
[#Example-259](http://spec.commonmark.org/0.20/#example-259)
[#Example-260](http://spec.commonmark.org/0.20/#example-260)
[#Example-261](http://spec.commonmark.org/0.20/#example-261)
[#Example-262](http://spec.commonmark.org/0.20/#example-262)
[#Example-265](http://spec.commonmark.org/0.20/#example-265)
[#Example-267](http://spec.commonmark.org/0.20/#example-267)
[#Example-541](http://spec.commonmark.org/0.20/#example-541)
[#Example-542](http://spec.commonmark.org/0.20/#example-542)

**Comment by jgm** [comment]
You get `<pre><code>` for code blocks, `<code>` for code spans.  There are some examples in the Code Blocks section of inputs that *don't* produce code blocks, and some of these produce code spans.  For example,

    ``` ```
    foo
    ```

doesn't produce a code block because the initial code fence can't contain spaces.  But it does produce an empty code span, since three backticks are a valid code span delimiter.

I hope this is enough for you to understand the behavior in the other examples, but let me know if you have specific questions.


+++ Aaron Power [Jun 13 15 03:13 ]:
>   The following examples use <p><code></code></p> where the rest use
>   <pre><code></code></pre>. Is this the actual behavior or just typos?
>
>   [1]#Example-90
>   [2]#Example-97
>   [3]#Example-230
>   [4]#Example-236
>   [5]#Example-254
>   [6]#Example-256
>   [7]#Example-257
>   [8]#Example-258
>   [9]#Example-259
>   [10]#Example-260
>   [11]#Example-261
>   [12]#Example-262
>   [13]#Example-265
>   [14]#Example-267
>   [15]#Example-541
>   [16]#Example-542
>
>   —
>   Reply to this email directly or [17]view it on GitHub.
>
>References
>
>   1. http://spec.commonmark.org/0.20/#example-90
>   2. http://spec.commonmark.org/0.20/#example-97
>   3. http://spec.commonmark.org/0.20/#example-230
>   4. http://spec.commonmark.org/0.20/#example-236
>   5. http://spec.commonmark.org/0.20/#example-254
>   6. http://spec.commonmark.org/0.20/#example-256
>   7. http://spec.commonmark.org/0.20/#example-257
>   8. http://spec.commonmark.org/0.20/#example-258
>   9. http://spec.commonmark.org/0.20/#example-259
>  10. http://spec.commonmark.org/0.20/#example-260
>  11. http://spec.commonmark.org/0.20/#example-261
>  12. http://spec.commonmark.org/0.20/#example-262
>  13. http://spec.commonmark.org/0.20/#example-265
>  14. http://spec.commonmark.org/0.20/#example-267
>  15. http://spec.commonmark.org/0.20/#example-541
>  16. http://spec.commonmark.org/0.20/#example-542
>  17. https://github.com/jgm/CommonMark/issues/333
