### ISSUE TITLE
Clarify URL-escaping (percent-encoding) of link destinations

### ISSUE THREAD

**Issue by robinst** [jgm/CommonMark#334]
The only mention of doing URL-escaping when rendering in the spec is that it's optional (and it's not clear to what part the "optionally URL-escaped" applies):

> URL-escaping should be left alone inside the destination, as all URL-escaped characters are also valid URL characters. HTML entities in the destination will be parsed into the corresponding unicode codepoints, as usual, and optionally URL-escaped when written as HTML.

Seeing as the example after the above uses escaping (`%C3%A4`), I implemented escaping for all characters except the [Reserved Characters](http://tools.ietf.org/html/rfc3986#section-2.2) and Unreserved Characters according to RFC 3986.

But this broke another example:

```
[foo<http://example.com/?search=][ref]>

[ref]: /uri
```

My implementation doesn't escape `[` and `]` because they are part of the Reserved Characters according to RFC 3986. It looks like older RFCs didn't include `[` or `]`, e.g. see JS's [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) function, which is what the current implementations mimic.

To decouple the specifics of percent-encoding from the spec, I would probably prefer if the spec examples didn't use any escaping (so `ä`, `[`, `]` and possibly others would be in the expected output), but left already percent-encoded letters intact. That would mean link destinations end up in the AST as is, except for entities like `&auml;` decoded to characters (and backslash-escapes).

**Comment by jgm** [comment]
+++ Robin Stocker [Jun 14 15 21:15 ]:
>   The only mention of doing URL-escaping when rendering in the spec is
>   that it's optional (and it's not clear to what part the "optionally
>   URL-escaped" applies):
>
>     URL-escaping should be left alone inside the destination, as all
>     URL-escaped characters are also valid URL characters. HTML entities
>     in the destination will be parsed into the corresponding unicode
>     codepoints, as usual, and optionally URL-escaped when written as
>     HTML.
>
>   Seeing as the example after the above uses escaping (%C3%A4), I
>   implemented escaping for all characters except the [1]Reserved
>   Characters and Unreserved Characters according to RFC 3986.
>
>   But this broke another example:
>[foo<http://example.com/?search=][ref]>
>
>[ref]: /uri
>
>   My implementation doesn't escape [ and ] because they are part of the
>   Reserved Characters according to RFC 3986. It looks like older RFCs
>   didn't include [ or ], e.g. see JS's [2]encodeURI function, which is
>   what the current implementations mimic.
>
>   To decouple the specifics of percent-encoding from the spec, I would
>   probably prefer if the spec examples didn't use any escaping (so ä, [,
>   ] and possibly others would be in the expected output), but left
>   already percent-encoded letters intact. That would mean link
>   destinations end up in the AST as is, except for entities like &auml;
>   decoded to characters (and backslash-escapes).

Officially we want to remain neutral on escaping -- it's a renderer issue.

So I think the best approach to this would be for `test/normalize.py` to normalize href and src attributes somehow.
