### ISSUE TITLE
Document parsing strategy for links and emphasis

### ISSUE THREAD

**Issue by jgm** [jgm/CommonMark#336]
The reference implementations have a strategy for parsing these without backtracking.
Document this clearly, and clean up and simplify the code where possible.  It is currently a bit too complex to be confident in its correctness.

Using two separate delimiter stacks would probably make things much clearer.

**Comment by jgm** [comment]
See https://github.com/jgm/cmark/blob/master/algorithm.md
for a start

**Comment by zudov** [comment]
I'll just leave it here. https://gist.github.com/zudov/bad6c3c518157e2c7071

This is a pretty raw implementation of Emphasis parsing in haskell (from my still unreleased library). Since most algorithm descriptions are very imperative this might be helpful to someone who implements it in a functional language.

**Comment by jgm** [comment]
+++ Konstantin Zudov [Jun 18 15 15:35 ]:
>I'll just leave it here. https://gist.github.com/zudov/bad6c3c518157e2c7071
>
>This is a pretty raw implementation of Emphasis parsing in haskell (from my still unreleased library). Since most algorithm descriptions are very imperative this might be helpful to someone who implements it in a functional language.

Thanks for posting.  I'm curious, how does this algorithm do on the
pathological tests in cmark (test/pathological_test.py)?

**Comment by zudov** [comment]
@jgm It's been doing badly, but yesterday I've rewritten it and now it handles those without exponential slowdowns. I'll try to post it soon.

**Comment by zudov** [comment]
Ah, wait. It wasn't that bad with the algorithm that I posted, it's just that link handling was bad which made the `'[' * 50000 + 'foo' + ' ']' * 50000` stale. I've merged the emph parsing with link parsing as described in algorithm.md, and it became much better. The emph parsing remained almost unchanged.
