### ISSUE TITLE
The logo and name should probably be changed

### ISSUE THREAD

**Issue by szhu** [jgm/CommonMark#341]
*Mirrored on [talk.commonmark.org](http://talk.commonmark.org/t/the-logo-and-name-should-probably-be-changed/1254) because I'm not sure which place is more appropriate*

---

I believe that the CommonMark name and logo too stubbornly hang on to branding associated with John Gruber's Markdown. I believe that this is bad for two reasons:

1. This is not respectful to John Gruber. While he might not technically have a copyright on it, he did request a few times for people to leave the Markdown branding alone. Each time, the project maintainers here backed off just enough to make him barely okay with it. And there are still definitely traces of the intention of the original branding, which basically is that CommonMark is "the real Markdown". My argument here is about intentions, not words. The idea behind every single iteration of the CommonMark name has been to try to become the "real" Markdown. (More examples: "CommonMark" sounds like an abbreviation of "common Markdown", and its "logo" literally says "mark down".) Given this, it looks like John Gruber's request was not really honored; he was just made unable to tell say objectively what is wrong with the current branding.

2. In addition, having CommonMark's branding tied to Markdown probably will hurt in the long run. This project is really successful and will probably become completely independent of Markdown sometime in the near future, and really deserves its own branding.

If there were no way around having this kind of branding, then doing all this might be acceptable. But I come with suggestions too!

  - I think this project should be renamed to "Mark," or something similar. I think it's quite hard to explain what the "Common" in "CommonMark" means without talking about Markdown, which is bad for the above two reasons.

  - The CommonMark current logo literally stands for "Markdown", which (1) Gruber said no to and (2) does not read as "CommonMark." I'm not a really good artist but I suggest some kind of logo that can be easily associated to the name of this project without knowledge of what Markdown is.

---

Notes

I say this with the most respect to all that this project has achieved, and even to all the branding consideration so far. It's only because this project is so popular and successful that I believe that branding needs to be considered this closely. In addition, I understand that this post sounds a bit inciting, but that's because I really want to hear people's feedback on this and re-iterate. Thanks for understanding!

I believe I've read through the most of the discussions surrounding CommonMark branding (see below), but I don't think any of them directly address these concerns. Please let me know if I'm missing anything—

 - https://github.com/jgm/CommonMark/issues/19
 - http://talk.commonmark.org/t/the-markdown-logo/14
 - http://talk.commonmark.org/t/project-name-appears-to-infringe-on-markdown-license-terms/337
 - http://blog.codinghorror.com/standard-markdown-is-now-common-markdown/

**Comment by jgm** [comment]
The talk page is the right place for this, so I'm closing this here.
