### ISSUE TITLE
test/spec_tests.py not working

### ISSUE THREAD

**Issue by Aaronepower** [jgm/CommonMark#344]
When `python test/spec_tests.py --dump-tests` is run the following error appears.
```
Traceback (most recent call last):
  File "test/spec_tests.py", line 127, in <module>
    print(json.dumps(tests, ensure_ascii=False, indent=2))
  File "C:\Python34\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 100: character maps to <undefined> 
```

Python version: `3.4.3`

**Comment by jgm** [comment]
I'm unable to reproduce this.  Python 3.4.3, OSX 10.9.5;
LANG=en_US.UTF-8.  I also tried it on Ubuntu.  More information on your
environment?  What is your locale?


+++ Aaron Power [Jul 03 15 07:58 ]:

**Comment by Aaronepower** [comment]
Oh sorry, I forgot to mention this is on windows 7.

**Comment by jgm** [comment]
Unfortunately, I don't know enough about character encoding
on Windows to help with this.  Maybe someone else can?

+++ Aaron Power [Jul 03 15 10:45 ]:

**Comment by jgm** [comment]
I think this change should fix your problem; it forces the output to be UTF-8 (which is desirable; we don't want the contents of the dumped json to vary depending on the platform you used to produce it).
Let me know if you still have the problem.
