### ISSUE TITLE
test/spec_tests.py --program error

### ISSUE THREAD

**Issue by Aaronepower** [jgm/CommonMark#345]
running `python test/spec_tests.py --program program.exe`

```
Traceback (most recent call last):
  File "test/spec_tests.py", line 134, in <module>
    do_test(test, args.normalize, result_counts)
  File "test/spec_tests.py", line 39, in do_test
    [retcode, actual_html, err] = cmark.to_html(test['markdown'])
  File "G:\commonmark\test\cmark.py", line 22, in <lambda>
    self.to_html = lambda x: pipe_through_prog(prog, x)
  File "G:\commonmark\test\cmark.py", line 9, in pipe_through_prog
    p1 = Popen(prog.split(), stdout=PIPE, stdin=PIPE, stderr=PIPE)
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Python Version: `3.4.3`
OS: `Windows 7 Ultimate`

**Comment by jgm** [comment]
Is program.exe in your working directory?  The argument to
`--program` is the path to the program.  It's not enough if
program.exe is in your system PATH.

+++ Aaron Power [Jul 04 15 02:55 ]:

**Comment by Aaronepower** [comment]
That worked however, I receive the following error, on example three. Seems to be the same problem as #344. Also what is being passed to the program? Mine is responding with no free arguments error. Is passing the test as a flag? What is the `spec-tests.py` also expecting to be returned?

```
Traceback (most recent call last):
  File "test/spec_tests.py", line 134, in <module>
    do_test(test, args.normalize, result_counts)
  File "test/spec_tests.py", line 55, in do_test
    sys.stdout.write(test['markdown'])
  File "C:\Python34\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u1f50' in position 13: character maps to <undefined>
```

**Comment by jgm** [comment]
See if the latest push helps with the unicode error.
Note, however, that now I'm forcing output as UTF-8, which
probably won't look right in your Windows console.  There's
probably a better approach.

`spec_test.py` feeds your program the Markdown test input as UTF-8
encoded bytes, and expects it to give HTML output as UTF-8
encoded bytes.

+++ Aaron Power [Jul 04 15 10:40 ]:

**Comment by Aaronepower** [comment]
I checked the printing on cmder, Powershell, and cmd, and it seemed fine. However printing out the argument list, shows nothing being passed to the program.

Example:
```
Example 184 (lines 2999-3011) List items
  10.  foo

           bar
--- expected HTML
+++ actual HTML
@@ -1,7 +1,3 @@
-<ol start="10">
-<li>
-<p>foo</p>
-<pre><code>bar
-</code></pre>
-</li>
-</ol>
+["G:\\rust-e\\target\\debug\\rust_e.exe"]
+ERROR:
+You must provide a file, or folder path as an argument.
```
The last three lines are from my program, the first being a printout of the argument list. The 2 being a self made error if nothing is passed to the program.

**Comment by cebe** [comment]
afaik the markdown is sent to the program using pipes not using a filename argument.

**Comment by Aaronepower** [comment]
The actual comment isn't important, it fails when there is no arguments passed in. And the line above it shows that when the program has started it doesn't think it has gotten any arguments.

**Comment by cebe** [comment]
that is what I wrote above, the program will not get any arguments, it will get the content piped to STDIN.

on unix terminal this would look like this:
```
echo "markdown" | yourpogram.exe
```

no idea how that works on windows.

**Comment by Aaronepower** [comment]
Ah, yes I was only taking in from environment variables.
