### ISSUE TITLE
"comment" facility in commonmark?

### ISSUE THREAD

**Issue by zaxebo1** [jgm/CommonMark#348]
1) the triple dash makes pandoc ignore the comment when it parses the markdown file. 

2) the Comments Plugin(https://github.com/ryneeverett/python-markdown-comments ) for python-markdown ( https://github.com/waylan/Python-Markdown ) , which implements the same pandoc commenting style mentioned above. 

3) But even if you use another markdown engine, the comment WILL show up in the generated HTML and so still be invisible on  render , until someone sees "view source". So it is graceful fallback.

4) NOTE: if you put double dash, then its HTML comment always -in pandoc and all other markdown processors
 
***

If we do not standardise then some will invent there own syntax like http://criticmarkup.com/ (superset of markdown) invents   >>This is comment<<     syntax.

It is great need to make a uniform comment syntax in all the markdown implementations.

The triple dash has an advantage of having a graceful fallback, that it will not showup in browser , even if it was not implemented.

***

Hence, I will request you that please include the triple dash    of pandoc as comment syntax of commonmark, which should not be rendered by the conforming implementations

**Comment by zaxebo1** [comment]
commenting is such a dire need. Markdown is used for documentation in many places. 
But documentation in the markdown raw file itself via uniform comment syntax (which does not render) - is itself not existing. 
Is it not an irony that documenting(commenting)  the file in documentation language (commonmark) itself not possible, as of now

**Comment by jgm** [comment]
>   1) the triple dash makes pandoc ignore the comment when it parses the
>   markdown file.

Pandoc doesn't actually work this way.  I recall suggesting
the idea once on the pandoc mailing list, but I don't think I ever
implemented it.

I agree, this is a nice idea.  Whether it belongs in the
spec is not so clear.

An implementation could always define an "ignore-comments"
option that throws out *all* HTML comments (or, just those
with a triple dash).  In a way, this is a rendering detail.

**Comment by zaxebo1** [comment]
Ooops.
Due to dire need of the uniform standard comment element , I googled and reached http://stackoverflow.com/questions/4823468/store-comments-in-markdown-syntax .
People were really wanting a uniform solution there too, and suggested that pandoc does this, and then there was some confusion.
So if you could add this syntax to pandoc and also to commonmark test suite, then it wil be great. From the above mentioned link it is clear that people are doing hackish solutions for this very core and natural need.

**Comment by zaxebo1** [comment]
> I agree, this is a nice idea. Whether it belongs in the spec is not so clear.

**Commenting should be part of spec**, in my humble opinion.   

**But just God forbid, if you did not added it to the spec, then please add it to pandoc atleast.**

**Comment by jgm** [comment]
I'm closing this, because more open-ended comments should go to http://talk.commonmark.org, not on this tracker.  Feel free to open a thread about comments there.

**Comment by zaxebo1** [comment]
@jgm : i have already posted a thread there at 
http://talk.commonmark.org/t/comment-facility-in-commonmark/1271/3
