### ISSUE TITLE
`make spec` returns "AttributeError: 'bytes' object has no attribute 'encode'" 

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/CommonMark#354]
After issue #353 was closed, now opening new issue (I cannot re-open #353, it seems -- and error message is a bit different now).

After doing a `git pull`, I'm ***still*** getting an error, now slightly different:

~~~
$ make spec
  
  python3 tools/makespec.py html > spec.html
  Traceback (most recent call last):
    File "tools/makespec.py", line 169, in <module>
      err("Error converting markdown version of spec:\n")
  TypeError: 'bytes' object is not callable
  make: *** [spec.html] Error 1
~~~

`make spec.md` and `make spec.pdf` do now work as expected.

**Comment by jgm** [comment]
OK, this particular problem should be addressed by
the latest push.  (It was just a typo.)

However, the fact that it's getting to the line
that emits an error message means something is
still not going to work for you -- at least now
we should see what it is.

+++ Kurt Pfeifle [Jul 28 15 13:02 ]:

**Comment by KurtPfeifle** [comment]
I've again updated, and my `makespec.py` now contains the line saying `err(err)`. However, the error message remains exactly the same:

~~~
$ make spec

  python3 tools/makespec.py html > spec.html
  Traceback (most recent call last):
    File "tools/makespec.py", line 169, in <module>
      err("Error converting markdown version of spec:\n")
  TypeError: 'bytes' object is not callable
  make: *** [spec.html] Error 1
~~~

**Comment by jgm** [comment]
+++ Kurt Pfeifle [Jul 28 15 14:28 ]:
>   I've again updated, and my makespec.py now contains the line saying
>   err(err). However, the error message remains exactly the same:

Sorry, I made an even dumber mistake this time.
(I've got to remember that python lets you shoot
yourself in the foot in ways that Haskell does not!)

**Comment by KurtPfeifle** [comment]
Ok, now it is this:

~~~
$ make spec

  python3 tools/makespec.py html > spec.html
  Error converting markdown version of spec:
  Traceback (most recent call last):
    File "tools/makespec.py", line 170, in <module>
      err(err_out)
    File "tools/makespec.py", line 13, in err
      sys.stderr.buffer.write(str.encode('utf-8'))
  AttributeError: 'bytes' object has no attribute 'encode'
  make: *** [spec.html] Error 1
~~~

**Comment by jgm** [comment]
Try it now.

+++ Kurt Pfeifle [Jul 28 15 15:12 ]:

**Comment by KurtPfeifle** [comment]
Now there's even less detail in the message:

~~~
$ make spec

  python3 tools/makespec.py html > spec.html
  Error converting markdown version of spec:
  make: *** [spec.html] Error 1
~~~

**Comment by jgm** [comment]
Have you installed cmark? (jgm/cmark)
This is used for the conversion.


+++ Kurt Pfeifle [Jul 28 15 15:59 ]:

**Comment by KurtPfeifle** [comment]
Yes. `cmark` is (and was) installed, and it is in `$PATH`.

**Comment by jgm** [comment]
Try the latest.  It's hard for me to debug remotely, though.
Do you know anything about python?  Can you figure out what
is happening?  This works fine for me.

+++ Kurt Pfeifle [Jul 29 15 11:06 ]:

**Comment by KurtPfeifle** [comment]
Sorry, I'm not knowing enough about Python to even be dangerous with it.

~~~
$ make spec

  python3 tools/makespec.py html > spec.html
  Traceback (most recent call last):
    File "tools/makespec.py", line 140, in <module>
      result = pipe_through_prog(prog, toc + mdtext)
    File "tools/makespec.py", line 40, in pipe_through_prog
      result = check_output(prog.split(), input=text.encode('utf-8'))
    File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 620, in check_output
      raise CalledProcessError(retcode, process.args, output=output)
  subprocess.CalledProcessError: Command '['cmark', '--smart']' returned non-zero exit status 1
  make: *** [spec.html] Error 1
~~~

**Comment by jgm** [comment]
It really looks as if it's not finding cmark in your path.
Try modifying makespec.py by adding an explicit path:

Change line 139 where it says

    prog = "cmark --smart"

to

    prog = "/usr/local/bin/cmark --smart"

(assuming /usr/local/bin is where your cmark executable
lives).  Also, what version of cmark is installed?  Maybe
you have an old version without --smart?

+++ Kurt Pfeifle [Jul 29 15 14:28 ]:

**Comment by KurtPfeifle** [comment]
***NOW*** we are getting somewhere!  :+1: 

Your suspicion was right. The `cmark` in my path v0.1. I re-compiled the latest, v0.21.0 and it now all works.

Thanks for your help, your patience and your persistency!  :)
