### ISSUE TITLE
Ambiguity in <pre> parsing

### ISSUE THREAD

**Issue by dikmax** [jgm/CommonMark#355]
By spec line starting with `<pre` could be parsed using rule 1 or rule 6 which can be ambiguous.
We should define rules precedence or remove 'pre' from tags in rule 6.

**Comment by jgm** [comment]
I think 'pre' should be removed from the list in rule 6.
The reference implementations should be updated accordingly.

+++ Maxim Dikun [Aug 02 15 08:50 ]:
