### ISSUE TITLE
cmark does not generate copyright symbol on windows

### ISSUE THREAD

**Issue by yangcha** [jgm/CommonMark#359]
Windows version of cmark does not correctly translate &copy; to copyright symbol in html format. It generates Â© instead.

**Comment by jgm** [comment]
The output of cmark is UTF-8 encoded.

If you're looking at the output in PowerShell, it's probably
not set up for UTF-8.

If you're viewing the output in a browser, tell your browser
that the content is UTF-8.  (In Google Chrome, you can do
this with View->Encoding.  I don't know about IE.  A better
approach is to make sure the HTML page has a meta tag
specifying the encoding.)

+++ Changjiang Yang [Aug 12 15 12:26 ]:

**Comment by jgm** [comment]
By the way, the issue tracker for cmark is at jgm/cmark.
This tracker is just for the spec itself.

**Comment by yangcha** [comment]
Yes, you are right. If I set the browser's encoding to UTF-8, then the
copyright sign is correctly displayed. Do you know how to specify the
encoding from either markdown document or better yet to specify from the
cmark option?

Thanks,

--Changjiang

**Comment by jgm** [comment]
cmark doesn't have encoding options; it's always UTF-8 (and
the input is expected to be UTF-8).  You can use iconv or a
similar tool to convert between this and other encodings.
