### ISSUE TITLE
+ `;` incorrectly parsed as list item in spec.txt

### ISSUE THREAD

**Issue by Jubobs** [jgm/CommonMark#360]
[Line of 4951 of `spec.txt`](https://github.com/jgm/CommonMark/blob/master/spec.txt#L4951) gets parsed and [rendered](http://spec.commonmark.org/0.21/#hexadecimal-entities) as a list item, but shouldn't be. This tripped me up when I was reading the CommonMark spec.

**Comment by jgm** [comment]
It's parsed correctly, according to the spec, since `+` can
start a list and lists need not be preceded by a blank line.

But obviously this isn't wanted, so I'll move the `+`.

+++ Jubobs [Aug 15 15 12:07 ]:

**Comment by Jubobs** [comment]
> It's parsed correctly, according to the spec, since `+` can
start a list and lists need not be preceded by a blank line.

Yes, sorry; I should have been more precise. Thanks for fixing it.
