### ISSUE TITLE
Provide a permanent URI to the most recent (released) version of the spec

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/CommonMark#362]
Currently, it is only possible to link to a hard-wired version of the spec on the CommonMark website, like:

* http://spec.commonmark.org/0.21/
* http://spec.commonmark.org/0.20/
* [....]

At this moment in time, v0.21 is the most recent version. However, I'd like to have an *additional* URI which looks like:

* http://spec.commonmark.org/current/

This should point to whichever newest version of the spec is released.

I recently had to supply some links about Markdown, CommonMark and Pandoc for an event's website. At the time, I linked to v0.20. When the spec changed to v0.21 the problem wasn't so much that I didn't get aware of the change very fast -- the problem was with all the hassle to get the event's website updated properly and in a timely manner. (No, I do not want to replace that link by just [spec.commonmark.org/](http://spec.commonmark.org/)...)

**Comment by jgm** [comment]
I intentionally didn't create a `/current/` endpoint.  I see
why you might want one, but I worry that people will just
start using this all the time, and then we'll have the
problem of broken links that we had before we had versioned
URLs for the specs...

**Comment by KurtPfeifle** [comment]
Couldn't this be solved with a HTTP redirection?

Or maybe I do not understand the problem?

Why couldn't people who want to link to a specific version's behavior not still do so by providing the versioned link?

**Comment by colinodell** [comment]
Would you consider using an HTTP redirect instead?  (Either 302, 303, or
307 - whichever you feel is most appropriate)

This would allow a direct link to the latest spec which both machines and
humans can properly understand.

**Comment by jgm** [comment]
+++ colinodell [Aug 17 15 10:50 ]:
>Would you consider using an HTTP redirect instead?  (Either 302, 303, or
>307 - whichever you feel is most appropriate)
>
>This would allow a direct link to the latest spec which both machines and
>humans can properly understand.

Redirect would work if I can figure out how to do it on
github pages.

**Comment by KurtPfeifle** [comment]
I found this link:

* https://help.github.com/articles/redirects-on-github-pages/

(though I don't understand completely what it explains)

**Comment by jgm** [comment]
+++ Kurt Pfeifle [Aug 17 15 12:28 ]:
>I found this link:
>
>* https://help.github.com/articles/redirects-on-github-pages/

Saw that but I don't use jekyll - just plain HTML pages.

**Comment by jgm** [comment]
OK, try http://spec.commonmark.org/current/

+++ colinodell [Aug 17 15 10:50 ]:

**Comment by KurtPfeifle** [comment]
Thanks a lot!

I tested with Chrome, Firefox + Safari on Mac OS X 10.10.5, and it works.
