### ISSUE TITLE
ENH: | literal blocks similar to > quoted blocks

### ISSUE THREAD

**Issue by westurner** [jgm/CommonMark#367]
In ReStructuredText, contiguous lines starting with "|" (pipe character) form a ["line block"](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#line-blocks), where newlines are newlines. For example:

```restructuredtext
.. index:: Markdown
.. _markdown:

Markdown
++++++++++
| Wikipedia: https://en.wikipedia.org/wiki/Markdown
| Homepage: `<https://daringfireball.net/projects/markdown/>`__
| Standard: https://daringfireball.net/projects/markdown/syntax
| Docs: http://www.w3.org/community/markdown/wiki/MarkdownImplementations
| Docs: http://learnxinyminutes.com/docs/markdown/
| Docs: https://guides.github.com/features/mastering-markdown/
| Docs: https://help.github.com/articles/github-flavored-markdown/
| Docs: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
| FileExt: ``.Md``
| FileExt: ``.md``

Markdown is a :ref:`Lightweight markup language`
which can be parsed and transformed to
valid :ref:`HTML-`.
````

Here, gh-flavored markdown parses the newlines (and the pipe character is obviously as-yet unsupported):

| ... from:
| Docs: https://wrdrd.com/docs/tools/#markdown

This would be really useful to have in the core markdown spec; and one or more implementations:
* http://www.w3.org/community/markdown/wiki/MarkdownImplementations

* Would it be possible to support | literal blocks in CommonMark?
  * Bakcward compatability? ``^|``
  * Tables?
  * Utility? Far easier than adding `` \`` or ``..``
    * My editor shouldn't be configured to auto-strip trailing spaces, but often

Status quo:

> It introduces an alternative syntax for hard line breaks, a backslash at the end of the line, supplementing the two-spaces-at-the-end-of-line rule. This is motivated by persistent complaints about the “invisible” nature of the two-space rule.
>
> [-- https://github.com/jgm/CommonMark/blob/3813179e83/README.md]

**Comment by jgm** [comment]
I am a big fan of the reST line block syntax.  For 1.0,
we're trying not to depart much from original Markdown, but
I'd be in favor of adding this at some point.

(I already support it in pandoc's Markdown.)

This isn't the right place to raise this discussion, though.
You should post on http://talk.commonmark.org.  This tracker
is not the place for extended discussion of new features.
