### ISSUE TITLE
Why <script </script> is acceptable?

### ISSUE THREAD

**Issue by wdhwg001** [jgm/CommonMark#368]
Even it will cause error in dingus page?

**Comment by jgm** [comment]
See http://spec.commonmark.org/0.22/#html-blocks (1)

We only require the beginning of a tag to start the HTML block.  This allows us to parse HTML blocks without backtracking -- we'll never have a situation where we start `<script`, then eventually decide we don't have a complete tag and need to backtrack, perhaps indefinitely.

This allows you to put in ill-formed HTML -- but with raw HTML, it's garbage in, garbage out.  Applications that allow users to input raw HTML should *always* sanitize.

If you want to discuss this design decision further, please open a topic on talk.commonmark.org.  This isn't the right place for extended discussions, so I'm closing this issue.
