### ISSUE TITLE
Spec markup: carriage return symbol on carriage returns in markdown text

### ISSUE THREAD

**Issue by srawlins** [jgm/CommonMark#371]
In the links section, see [example 448](http://spec.commonmark.org/0.22/#example-448) and [example 455](http://spec.commonmark.org/0.22/#example-455). The spec discusses in 448 that destinations can't contain line breaks. But it _looks like_ 455 does contain a line break. On second look, its probably that the line is wrapped.

Can the spec portray line breaks with a [carriage return symbol](https://en.wikibooks.org/wiki/Unicode/List_of_useful_symbols#Typography) maybe, on the left-hand Markdown texts when a newline exists? Similar to the muted bullets that exist to depict space characters.

**Comment by jgm** [comment]
+++ Sam Rawlins [Oct 12 15 07:49 ]:
>   In the links section, see [1]example 448 and [2]example 455. The spec
>   discusses in 448 that destinations can't contain line breaks. But it
>   looks like 455 does contain a line break. On second look, its probably
>   that the line is wrapped.

Yes, it's soft-wrapped.  We have css

    pre { white-space: pre-wrap }

>   Can the spec portray line breaks with a [3]carriage return symbol
>   maybe, on the left-hand Markdown texts when a newline exists? Similar
>   to the muted bullets that exist to depict space characters.

That's a possibility, but it's important to maintain
cut-and-pasteability, and it would clutter up the visuals.

Other options I can think of:

- using a shorter example to avoid soft-wrapping
- using different CSS so a scroll-bar is created in this
  case

Not sure what is best, but thanks for pointing out the issue.
