### ISSUE TITLE
The 'link' portion of the spec never mentions parentheses.

### ISSUE THREAD

**Issue by jdmarshall** [jgm/CommonMark#374]
None of the examples in the link section (starting with Example 144) mention parenthesis can delimit the text of an anchor.  

I would think it would make more sense for the first example to include this format (especially since none of the other examples seem to work when you want a link in the middle of a block of text)

**Comment by jgm** [comment]
Sorry, I'm not sure what you're talking about, and Example
144 has nothing to do with links.  Could you be more specific
and give an example?

+++ Jason Marshall [Oct 29 15 20:08 ]:

**Comment by jdmarshall** [comment]
> Example 144 has nothing to do with links

Sorry?  http://spec.commonmark.org/0.21/#example-144 

There is not a single example in the spec of [click here](http://www.example.com).  The entire section omits the most straightforward use of links in the spec, and talks instead about all of the multiline corner cases.

**Comment by jgm** [comment]
Note the organization of the spec:  the first part covers block-level elements, the second inline-level.  Links are in the latter.  In addition, there's a table of contents at the top, so if you want to know about Links, you need only to click on that entry in the table of contents.

In addition, right at the top of the section you're confused by, you can find this:

> A link reference definition does not correspond to a structural element of a document. Instead, it defines a label which can be used in reference links and reference-style images elsewhere in the document. Link reference definitions can come either before or after the links that use them.

Here "reference links" is a hyperlink that takes you right to the section on links.

The spec is not really intended as a simple introduction for beginners learning CommonMark.  (If you were trying to learn HTML, would you go to the HTML5 spec?)  For people who know nothing about Markdown, I'd recommend Gruber's original Markdown syntax description or something like http://eherrera.net/markdowntutorial/.
