### ISSUE TITLE
Implementation bias in CommonMark spec (wrt &#45; &#xA0; &amp; and so on)

### ISSUE THREAD

**Issue by tin-pot** [jgm/CommonMark#375]
In section "6.2 Entities" of the _CommonMark_ spec the issue of HTML (or XHTML, or XML, or SGML) "entities" is discussed, apparently meaning strings like `&#45;`, `&#xA0;`, `&amp;` that appear frequently in HTML (or ...) documents.

I can guess what is meant, but it is said in a rather fuzzy way:

The specification unfortunately talks in terms of "HTML Entities" and worse about storing _Unicode characters_ in "the AST", or the kind of output that "renderers" receive: all of this has no place in a _CommonMark_ specification IMO. This current wording has multiple flaws (independant from the intended meaning; the wording is:

 1. too HTML-centric (*numeric character references* are at the core of HTML and XML, namely inherited from SGML);

 2. wrong in the sense that eg "`&amp;`" is not an entity, but an *entity reference*,

 3. misleadingly wrong in the case of "`&#45;`" which has nothing to do with entities or entity references, but is a (*numeric*) *character reference*,

 4. too implementation-centric: what is relevant (for _CommonMark_ authors and implementors) is whether the _CommonMark_ parser "sees" the *replaced* characters or the literal *character references*: it turns out the former, but this has nothing to do with "storing Unicode characters in the AST", or what kind of output a "renderer receives".

I think that the CommonMark specification should talk only about the syntactic conventions used in _CommonMark_ as far as possible, and refrain from prescribing implementation details.

Particulary problematic is the use of the acronym "AST":

  - Neither the full term "Abstract Syntax Tree" (I assume this is meant!),

  - nor any definition of this _computer science_ jargon term,

  - not even a link to [Wikipedia][ast] is given.

  - While not every _CommonMark_ processor will even build an AST either.

A reader of the spec with *no CS background* will probably feel kind of helpless&nbsp;&hellip;

I think the term "AST" is used here to allude to an abstract concept, namely that a _CommonMark_ processor *detects and uses "the structure"* inscribed in the input text in some way, and the spec is meant to *define this way* (kind-of an operational semantics).

"The structure" is again a rather elusive term, but in the _CommonMark_ case it *coincides exactly* with (a part of) the "structure and content" of an HTML (or XML, or XHTML, or SGML) document: what is meant is the _[Information Set][is]_ of the "target document" which the processor has to discover, use, and output in some form or another.

For the simple case of _CommonMark_ "structured documents", it consists of:

  - a *nested structure* of "elements" (having "types" and "attributes"),

  - and (_Unicode_) *character content* inside (some of) these "elements".

This could probably be explained in a reasonably simple way by referring to some kind of concrete representation of the structure "discovered" in the _CommonMark_ text, ie by answering questions like:

  - where do the _nested elements_ (ie a heading, a paragraph, a list item) start and end?

  - how are chunks of the input text used as _character content_ for these _nested elements_ (that's where the *character references* come in again)?
  
Answers could be "demonstrated" maybe by presenting the corresponding _CommonMark_ "native" XML fragments (to alleviate a bit the heavy HTML bias throughout the spec), or in some form of (tree-like?) diagrams, and so on.

But it would sure be helpful to have some table or list of "element types", together with their "attributes" and other properties, to get an overview of what kind of "structured document" we're talking about.

And because the _CommonMark_ DTD is (supposed to be) tailored to match the abstract structure of the content of a _CommonMark_ text, it *should* be a better reference for explaining that structure than HTML (which has *a lot* of other "elements", "attributes", and peculiarities).

[is]:http://www.w3.org/TR/xml-infoset/
[ast]:https://en.wikipedia.org/wiki/Abstract_syntax_tree

**Comment by jgm** [comment]
Action items:

- Remove or rephrase the two references in the spec to the "AST"
- Fix terminology: `&amp` is an entity reference, not an entity; `&#45;` is a numeric character reference.
