### ISSUE TITLE
Typo in a reference

### ISSUE THREAD

**Issue by dumblob** [jgm/CommonMark#389]
The phrase `[setext heading line]` seems to be used instead of `[setext heading line](@)`. Please take a look at the images attached.

![commonmark-diff](https://cloud.githubusercontent.com/assets/2451044/12533180/ec42193c-c227-11e5-964e-a4d6e0f9d323.png)

![commonmark-render](https://cloud.githubusercontent.com/assets/2451044/12533181/f1d7d846-c227-11e5-8df4-b1e074e4badd.png)

**Comment by jgm** [comment]
Thanks!  It was an inconsistency in the terminology.
