### ISSUE TITLE
Fix adorable mistake

### ISSUE THREAD

**Issue by pickfire** [jgm/CommonMark#391]
Hi, I found that the latest version of spec.commonmark.org is last written 2015-01-12 and the older version is written even later. Isn't it funny?

Good luck and have a nice day!

**Comment by cebe** [comment]
duplicate of #388 and fixed by https://github.com/jgm/CommonMark/commit/039157d8a65d8476368657ce372f458266460ca7 already.

**Comment by pickfire** [comment]
@cebe, but why is the website still showing the wrong time?

**Comment by jgm** [comment]
We just haven't done a release since the change was made.

+++ Ivan Tham [Feb 02 16 21:19 ]:
