### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by mcandre** [jgm/CommonMark#392]
Please add support for checkboxes, like GitHub-Flavored Markdown `* [x]`/`* [ ]` checked/unchecked syntax. This way, websites that use CommonMark checkbox syntax can add WYSIWYG Markdown checkboxes, a great feature for tracking work done in complex tickets!

**Comment by jgm** [comment]
Please raise discussion items at talk.commonmark.org.  This tracker is for simple actionable items that don't need a lot of discussion.
