### ISSUE TITLE
nested ordered lists indented with 2 spaces are broken

### ISSUE THREAD

**Issue by slang800** [jgm/CommonMark#399]
According the [list-items](http://spec.commonmark.org/0.25/#list-items) rule (that sublists need to be indented to the column of the first non-whitespace character after the list marker), the following Markdown:

```markdown
1. item
2. another item

  1. sub-list item
  2. sub-list another item
  3. sub-list last item

3. last item
```

Represents a single non-nested list:

```html
<ol>
  <li><p>item</p></li>
  <li><p>another item</p></li>
  <li><p>sub-list item</p></li>
  <li><p>sub-list another item</p></li>
  <li><p>sub-list last item</p></li>
  <li><p>last item</p></li>
</ol>
```

Which seems wrong, because using a 2-space indent is enough to have the list rendered correctly with [marked](https://github.com/chjj/marked/), redcarpet (& therefore GitHub), the original Markdown implementation, and PHP Markdown (see comparison on [Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=1.+item%0A2.+another+item%0A%0A++1.+sub-list+item%0A++2.+sub-list+another+item%0A++3.+sub-list+last+item%0A%0A3.+last+item%0A)).

I haven't gotten any stats yet on how popular 2 space indents are among people who write Markdown, but since there's at least one [styleguide](https://github.com/carwin/markdown-styleguide) recommending it, I think it's more than an edge-case.

For people who are thinking about indentation in terms of the number of spaces before the list marker, it's quite strange that you can use 2 spaces to nest a list within an unordered list, but need at least 3 spaces to nest within an ordered one. The absurdity of this rule is illustrated further when you have ordered lists in the 2-3 digit range:

```markdown
99. list item 99

    - sublist item
    - sublist item 2

100. list item 100

    - sublist item
    - sublist item 2
```

The tutorial at http://commonmark.org/help/tutorial/10-nestedLists.html says:

> To nest one list within another, indent each item in the sublist by four spaces.

...But that doesn't work in the above example because once you get above 100 you need to switch to 5-space minimum indents (see comparison on [Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=99.+list+item+99%0A%0A++++-+sublist+item%0A++++-+sublist+item+2%0A%0A100.+list+item+100%0A%0A++++-+sublist+item%0A++++-+sublist+item+2%0A)).

I've read the ["motivation" section](http://spec.commonmark.org/0.25/#motivation) of the spec discussing this rule, but I'm unconvinced because cases like:

```markdown
1.  foo

        indented code
```

...Are already [handled perfectly](http://johnmacfarlane.net/babelmark2/?normalize=1&text=1.++foo%0A%0A++++++++indented+code) by all parsers. And cases like:

```markdown
10. foo

   bar
```

...Probably _should_ be read as a list item with a subparagraph.

A few other discussions have covered the same topic:

- https://github.com/npm/newww/issues/1228
- http://talk.commonmark.org/t/could-also-support-two-spaces-for-list-indentation/2022
- http://talk.commonmark.org/t/indentation-requirement-of-sub-lists-inside-ordered-list-items/875

PS: The "changing the bullet or ordered list delimiter starts a new list" rule is an awful thing to put in the standard. [No other parsers do that](http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+foo%0A-+bar%0A%2B+baz).

**Comment by jgm** [comment]
The two-space rule is explicitly discussed in the spec
(along with various other rules).  Please see the
discussion in http://spec.commonmark.org/0.25/#motivation
for a full explanation of why we didn't go with this
option.

marked and redcarpet are not even consistent about the
two-space rule.  See
http://johnmacfarlane.net/babelmark2/?normalize=1&text=+1.+a%0A+++2.+b%0A+++++3.+c%0A+++++++4.+d%0A

Anyway, this tracker is not the place for open-ended
discussion about the spec (substantive issues).
That belongs in talk.commonmark.org.


+++ Sean Lang [Mar 31 16 21:39 ]:

**Comment by slang800** [comment]
Moved the post to http://talk.commonmark.org/t/nested-ordered-lists-indented-with-2-spaces-are-broken/2064, but had to break most of the links to get it to work.
