### ISSUE TITLE
Fixing Code blocks and adding Sample blocks

### ISSUE THREAD

**Issue by felixsanz** [jgm/CommonMark#404]
In the spec we have **Indented code blocks** and **Fenced code blocks**.

By definition, **code** block means **code**. This has nothing to do with the `<pre>` tag that is produced in the output, even if we're supposed to maintain white-space in the code output.

Because of this, it's impossible in any current implementation to add attributes into the `<code>` tags. For example in pandoc you can do:

    ```{.foo}
    command
    ```
Which produces `<pre class="foo"><code>command</code></pre>`.

See? We are applying attributes to the `<pre>` tag. How is that even correct? if the four spaces/three backticks means "indented/fenced **CODE** blocks", we're not applying attributes to the **code**!.

And, if we have the ability to create **input** (code tags), where is the ability to create **output** (samp tags) ?

Example: `<pre><samp>result</samp></pre>`.

This could be done with something like this (only fenced):

    ´´´{.foo}
    command
    ´´´

What do you think?

**Comment by arve0** [comment]
The implementation markdown-it [does apply the class to the code block](https://jsfiddle.net/ge0rqw46/1/).

**Comment by felixsanz** [comment]
@arve0 That's right, some does. But that's the only attribute you can add to the `<code>` tag and it's 	
arguable that is right, because i would add a data-language="" attribute, instead of a class which here is not semantically correct at all.

Since the spec doesn't say anything about adding attributes to tags, this is a possible bug on the pandoc implementation due to the language class being added to `<pre>` instead of `<code>` (instead of commonmark related).

But still, this issue could provide discussion about the inverse ticks `´´´` syntax for sample tags (output)! :)

**Comment by jgm** [comment]
This doesn't really belong here.  This tracker is for discussion of the CommonMark spec, not implementations.  All the spec says about this is:

> Opening and closing spaces will be stripped, and the first word, prefixed
> with `language-`, is used as the value for the `class` attribute of the
> `code` element within the enclosing `pre` element.

Use of the class attribute for this, rather than data-language, probably makes sense given the current state of things (not everyone on HTML5, and widespread use of highlighting libraries that assume a certain behavior).  But the spec really only defines the parse tree and makes recommendations about HTML output, so implementations have some flexibility on this.

**Comment by jgm** [comment]
PS. pandoc does attach classes that correspond to languages to the code tag:
```
% pandoc 
``` ruby
x = 5
```
<div class="sourceCode"><pre class="sourceCode ruby"><code class="sourceCode ruby">x = <span class="dv">5</span></code></pre></div>
```
It also attaches this to the pre tag, since sometimes this is necessary to get the background styled correctly.

**Comment by jgm** [comment]
You might want to bring this up as a discussion item on talk.commonmark.org.
(Search for related threads first.)
