### ISSUE TITLE
Ordered lists versus Czech language

### ISSUE THREAD

**Issue by mity** [jgm/CommonMark#405]
The CommonMark specification of [ordered lists](http://spec.commonmark.org/0.25/#list-items) clashes with Czech language in quite a cumbersome way: In Czech, the ordering numbers are written as "1., 2., 3., 125." (corresponding to English "1st, 2nd, 3rd, 125th").

Furthermore, using the ordering numbers is the correct and common way how to write dates in Czech, making the issue quite prominent. For example:
```
12. března 1999 se Česká republika spolu s Maďarskem a Polskem připojila k Severoatlantické alianci. 
1. 5. 2004 se pak stala členským státem Evropské unie.
```

(I enclosed the example into the code block to avoid same issues in github's Markdown.)

Although it is always possible to reformulate it, it is pain to do so constantly when authoring any documents in Markdown or when converting them from other formats.

Maybe some future version of the specification could do order lists a bit more stricter to distinguish them more explicitly from a paragraph starting with a number and dot? (E.g. non-zero indentation of the list marker and/or of the list item contents after the marker?)

Some other European languages use the same notation for ordering numbers and/or dates too.

**Comment by jgm** [comment]
I think that the suggestion (currently under consideration)
to disallow an ordered list immediately following a
paragraph (without an intervening blank line) will help a
bit with this.  But it won't help with the case where a
number followed by a period occurs at the beginning of a
paragraph.  There, you'll just need to backslash-escape
the period.

I think that requiring nonzero indent or > 1 space after
the period would be too great a departure from established
Markdown practice to contemplate here.

Hopefully the case where a paragraph starts with a date is
rare enough that this won't be a huge problem in practice.
