### ISSUE TITLE
Escape URI

### ISSUE THREAD

**Issue by xoofx** [jgm/CommonMark#413]
Hi,

Having some issues with links incorrectly escaped, I discovered that the specs escape URI that I would not expect to be escaped:

for example in [autolinks](https://github.com/jgm/CommonMark/blob/ee779cb7f8ea3c6274aef89f9916931b907e211e/spec.txt#L8404):

```````````````````````````````` example
<http://foo.bar.baz/test?q=hello&id=22&boolean>
.
<p><a href="http://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean">http://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean</a></p>
````````````````````````````````
Or in the links: http://spec.commonmark.org/0.25/#example-470

Why the URL is not kept as is, as the `&` is actually part of the query string?

Also this statement is a bit annoying in the specs:

> These may be optionally URL-escaped when written as HTML, but this spec does not enforce any particular policy for rendering URLs in HTML or other formats. Renderers may make different decisions about how to escape or normalize URLs in the output.

because we are using HTML to match the structure, we use a renderer specific output to verify the spec. It means that I would have to activate a specific link renderer for the spec and deactivate when not for the specs?

**Comment by xoofx** [comment]
Though, [many markdown](https://babelmark.github.io/?text=%3Chttp%3A%2F%2Ffoo.bar.baz%2Ftest%3Fq%3Dhello%26id%3D22%26boolean%3E) parser are actually escaping as CommonMark specs...

**Comment by jgm** [comment]
`&` must always be escaped in HTML, even in URLs.
See e.g.  http://www.htmlhelp.com/tools/validator/problems.html
http://burnignorance.com/web-development-tips/using-ampersands-s-in-urls/

Many browsers are forgiving about this, but the correct
thing to do is to escape the `&`.

+++ Alexandre Mutel [Jun 28 16 14:35 ]:

**Comment by xoofx** [comment]
ah sorry, the urls in the browser address are indeed confusing as they are almost never escaped...
