### ISSUE TITLE
Understanding of JSON output

### ISSUE THREAD

**Issue by rplCloud** [jgm/CommonMark#414]
Hi all,

I try to get JSON output using this library.

I tried the Python library and the cmark command line tool with the same results. HTML and AST looks ok for me:

```bash
cmark  <<< '*hello!*'
```
```html
<p><em>hello!</em></p>
```
```bash
cmark -a <<< '*hello!*'
```
```
[document]
	Title:
	Info:
	Destination:
	Sourcepos: [[1, 1], [1, 8]]
	Info:
	Literal:
	Children:
		-> [document]
			-> Title:
			-> Info:
...

```

But I do not understand the JSON output:

```bash
cmark -aj <<< '*hello!*'
```
```json
{"is_fenced": false, "t": "document", "sourcepos": [[1, 1], [1, 8]], "fence_length": 0, "open": false, "last_line_blank": false}
```

Honestly, I have no idea what this all about...

I expect some like this:

```json
[ "paragraph" , [
  [ "emph" , {} , [
    [ "text" , {} , [ "hello"
...
```

Can you give me some hints what I am oing wrong?

Regards,
Reto

**Comment by jgm** [comment]
You appear to be asking a question about a Python
implementation of CommonMark that provides a cmark
command, not the jgm/cmark library, which does not
have options `-a` or `-aj`.

Please direct your question to that implementation's
repository rather than here.

+++ rplCloud [Jul 04 16 12:34 ]:

**Comment by rplCloud** [comment]
Yes, you are right. Sorry!
