### ISSUE TITLE
List starts in lazy continuation line

### ISSUE THREAD

**Issue by wahlbrink** [jgm/CommonMark#420]
From spec:
> In order to solve of unwanted lists in paragraphs with hard-wrapped numerals, we allow only lists starting with 1 to interrupt paragraphs.

```
So the next line is
3) a lazy continuation line.
```

But:
```
1. This is a list
2. Why the next line is not
3) a lazy continuation line but interrupts a paragraph?
```

I know, "Changing the bullet or ordered list delimiter starts a new list", but the spec text is not clear to me which rule has priority. I would prefer lazy continuation, but Example 263 says new list. 

---
refers to spec 0.26

**Comment by jgm** [comment]
Yes, this definitely needs clarification. Thanks.

**Comment by jgm** [comment]
There's a kind of circularity here.  Whether
```
2. Why the next line is not
```
counts as a paragraph continuation line depends on whether it would be parsed as a line in a paragraph, which in turn depends on whether it would be parsed as a list item.

Argh!
