### ISSUE TITLE
ID Attribute in Headings

### ISSUE THREAD

**Issue by TheBrenny** [jgm/CommonMark#426]
This isn't an ambiguity in the spec, and I don't think it was ever part of the spec, but something that has definitely been implemented quite often in Markdown parsers is the way it handles Headings. GitHub for example, adds the `id` attribute to the heading, allowing it to be linked back to.

I feel this will be a discussion that will last until the dusk of Markdown comes, but it's a necessary discussion to have, in my opinion.

**Comment by jgm** [comment]
This is a complex issue that needs to be discussed in the forum.  If you look at talk.commonmark.org, you'll see a long thread on this already.  Feel free to contribute there. I'm closing this, since this tracker is for issues that don't require extended discussion.
