### ISSUE TITLE
Shortcut reference link with paren after it

### ISSUE THREAD

**Issue by dikmax** [jgm/CommonMark#427]
Consider this example:

```markdown
[link](Some text, not link)

[link]: asdf
```

Spec says:

> A shortcut reference link consists of a link label that matches a link reference definition elsewhere in the document and is not followed by `[]` or a link label. The contents of the first link label are parsed as inlines, which are used as the link’s text. The link’s URI and title are provided by the matching link reference definition. Thus, `[foo]` is equivalent to `[foo][]`.

It looks like the example above should be a link, but it doesn't. I think we should add an explanation to spec why not, or fix commonmark.js if it should be parsed that way.

**Comment by jgm** [comment]
I'm calling this an implementation bug.
