### ISSUE TITLE
Headings are nested in <p> elements

### ISSUE THREAD

**Issue by zzzzBov** [jgm/CommonMark#430]
Raw HTML headings (h2-h6) are wrapped in `<p>` elements.

[example][1]

```
<h1>lorem</h1>

<h2>lorem</h2>

<h3>lorem</h3>

<h4>lorem</h4>

<h5>lorem</h5>

<h6>lorem</h6>
```

produces

```
<h1>lorem</h1>
<p><h2>lorem</h2></p>
<p><h3>lorem</h3></p>
<p><h4>lorem</h4></p>
<p><h5>lorem</h5></p>
<p><h6>lorem</h6></p>
```

[1]: http://spec.commonmark.org/dingus/?text=%3Ch1%3Elorem%3C%2Fh1%3E%0A%0A%3Ch2%3Elorem%3C%2Fh2%3E%0A%0A%3Ch3%3Elorem%3C%2Fh3%3E%0A%0A%3Ch4%3Elorem%3C%2Fh4%3E%0A%0A%3Ch5%3Elorem%3C%2Fh5%3E%0A%0A%3Ch6%3Elorem%3C%2Fh6%3E

**Comment by zzzzBov** [comment]
@jgm, thanks for the quick fix! What's involved in updating `try.commonmark.org`?

**Comment by jgm** [comment]
It gets updated each time there's a new CommonMark release.

+++ Timothy [Sep 12 16 07:01 ]:
