### ISSUE TITLE
Quoted text not like used in email conversations

### ISSUE THREAD

**Issue by alinex** [jgm/CommonMark#440]
I have the markdown:

    > Stefan said:
    > > I would like to visit a castle in north scotland, next year.
    > But my home is my castle

The first line goes as level 1 blockquote, the second as level 2. But why is the third line added also to level 2 blockquote instead of the outer blockquote.

It would be nice if the common handling from quoting in plain text mails could be applied here, too.  I think this is also what everybody thinks the markdown should be read.

**Comment by jgm** [comment]
+++ Alexander Schilling [Nov 28 16 13:06 ]:
>   I have the markdown:
>> Stefan said:
>> > I would like to visit a castle in north scotland, next year.
>> But my home is my castle
>
>   The first line goes as level 1 blockquote, the second as level 2. But
>   why is the third line added also to level 2 blockquote instead of the
>   outer blockquote.

See the spec (or John Gruber's original Markdown syntax
description) under "lazy" and "laziness."

>   It would be nice if the common handling from quoting in plain text
>   mails could be applied here, too. I think this is also what everybody
>   thinks the markdown should be read.

Laziness is part of Markdown. Although my preferences align
with yours, this can't be changed without lots of backwards
incompatibility (and many complaints).

**Comment by cebe** [comment]
@alinex spacing matters, so this will work as expected:

```markdown
> Stefan said:
> > I would like to visit a castle in north scotland, next year.
>
> But my home is my castle
```

http://spec.commonmark.org/dingus/?text=%3E%20Stefan%20said%3A%0A%3E%20%3E%20I%20would%20like%20to%20visit%20a%20castle%20in%20north%20scotland%2C%20next%20year.%0A%3E%0A%3E%20But%20my%20home%20is%20my%20castle

**Comment by alinex** [comment]
Great that helps, i will use a quoted empty line.
