### ISSUE TITLE
AST as standard instead of HTML

### ISSUE THREAD

**Issue by anderflash** [jgm/CommonMark#441]
I think CommonMark should represent the parsed code primarily as AST (JSON) instead of HTML. For software development other than Web apps, this neutral format could be better, because it approximates the document tree in memory and we can develop directly our parsers. With AST, we isolate the different outputs.

[One example from Textlint](http://textlint.github.io/markdown-to-ast/example/)

HTML could be an example of output.

Thanks

**Comment by jgm** [comment]
See #274

**Comment by jgm** [comment]
Closing as a dup
