### ISSUE TITLE
[website] Announcement for 1.0 outdated

### ISSUE THREAD

**Issue by batisteo** [jgm/CommonMark#447]
The last line of the [commonmark.org](commonmark.org) website is outdated:
> With your help, we plan to announce a finalized 1.0 spec and test suite in early 2016. 

You might want to update it.

**Comment by jgm** [comment]
@codinghorror - you maintain that page, I believe.

+++ Baptiste Darthenay [Feb 08 17 08:01 ]:

**Comment by batisteo** [comment]
Thanks!
