### ISSUE TITLE
Handle Image title edge cases

### ISSUE THREAD

**Issue by aleemb** [jgm/CommonMark#455]
```
// works
![
Hello
World
](http://commonmark.org/help/images/favicon.png)

// fails
![
# Hello
World
](http://commonmark.org/help/images/favicon.png)


// works
![# Hello
World
](http://commonmark.org/help/images/favicon.png)
```

The second scenario should handle `#` as a regular character.

Though in my case, I would prefer to have a fancy image caption (instead of title) which would allow for markdown.

**Comment by jgm** [comment]
+++ aleemb [Apr 04 17 01:18 ]:
>// works
>![
>Hello
>World
>](http://commonmark.org/help/images/favicon.png)
>
>// fails
>![
># Hello
>World
>](http://commonmark.org/help/images/favicon.png)
>
>   The second scenario should handle # as a regular character.

Actually no -- because block level parsing always takes
precedence over inline level parsing.

**Comment by aleemb** [comment]
@jgm I added a third scenario as an edit. Not sure if that highlights an inconsistency or it is expected behaviour:

```
// works
![# Hello
World
](http://commonmark.org/help/images/favicon.png)
```

**Comment by jgm** [comment]
+++ aleemb [Apr 04 17 02:21 ]:
>   [1]@jgm I added a third scenario as an edit. Not sure if that
>   highlights an inconsistency or it is expected behaviour:
>// works
>![# Hello
>World

That's expected.  An ATX header can't have preceding text.
