### ISSUE TITLE
Definition for left- and right- flanking delimiter run is unclear

### ISSUE THREAD

**Issue by fiveop** [jgm/CommonMark#467]
The definitions for left- and right- flanking delimiter run contain the phrase "either ... or ...". With my math background, I read this as an exclusive or, which resulted in failing tests in my implementation.

In the C implementation it is implemented as if the "either ... or ..." was to be understood as an inclusive or (see https://github.com/jgm/cmark/blob/master/src/inlines.c#L333). This makes more sense and yielded passing tests for me.

I propose removing the word "either" from both definitions. The enumeration using (a) and (b) already provides the equivalent of correct parentheses in a logical formula.

(In addition, the cmark code could be amended to read (!A || B || C) instead of !(A && !B && !C) (starting from line 334 in inlines.c) to match the definition and (assuming the compiler cannot optimize it itself) save a few evaluations of B and C if !A is already true.)

**Comment by jgm** [comment]
Good suggestions, thanks.
