### ISSUE TITLE
Escape at end of link reference definition's link label

### ISSUE THREAD

**Issue by ScottAbbey** [jgm/CommonMark#468]
The C and Javascript reference implementations disagree on the following input:

```
[\ ]

[\]: test
```

The Javascript one sees this as a valid link label and link reference definition, the C one says it's two paragraphs.

I can't quite tell for sure which one is wrong, but it's probably a bug in the implementation of one or the other.  I'll post this here and hopefully someone who knows can send it the right direction.

Possibly related:

Ref: https://github.com/jgm/commonmark.js/issues/38
Ref: https://github.com/jgm/CommonMark/issues/325

**Comment by jgm** [comment]
I'd say the C implementation is right here.  The spec says
clearly that `]` is backslash-escapable in this context,
which means that

    [\]: test

isn't a valid link reference definition, but rather a
normal paragraph.
