### ISSUE TITLE
Setext headings after paragraphs preceded by link reference definitions

### ISSUE THREAD

**Issue by ScottAbbey** [jgm/CommonMark#470]
From section 4.3, Setext headings:
> A setext heading consists of one or more lines of text...The lines of text must be such that, were they not followed by the setext heading underline, they would be interpreted as a paragraph: they cannot be interpretable as a code fence, ATX heading, block quote, thematic break, list item, or HTML block.

I was surprised that the following input:
```
[a]: a
text
===
```
Results in this output from the reference implementation:
```
<h1>[a]: a
paragraph</h1>
```

It seems wrong that the presence of `===` several lines later would unmake the link reference definition on the first line of this input.

I have tried to determine if this is the intended behavior or not, but the spec seems a little under-specified here.  The preceding lines are not `a code fence, ATX heading, block quote, thematic break, list item, or HTML block`, so that portion of the rule doesn't seem to apply.

If the input was not followed by a setext heading underline, it would have resulted in a link reference definition (no visible output) followed by a paragraph.  It seems to me like adding both preceding lines of text to the heading is incorrect, since only the second one would have been interpreted as a paragraph.

Before trying this example out in the reference implementation, I expected it would produce this output:
```
<h1>text</h1>
```

The majority of Babelmark seem to agree with me, but that doesn't necessarily help me know what's expected here.

Is this one a bug in the reference implementations or are they working as intended? If the latter, it might be necessary to be a bit more specific in the spec.

**Comment by jgm** [comment]
Dup of #395?

**Comment by ScottAbbey** [comment]
Yes, I failed to locate it with search. Sorry.

Looks like we came to the same conclusions.

**Comment by jgm** [comment]
OK, closing in favor of the other: please feel free to comment there.
