### ISSUE TITLE
HTML entities in text are auto-converted to target symbols

### ISSUE THREAD

**Issue by MurzNN** [jgm/CommonMark#484]
When I type text with HTML entities like `&tcy;&iecy;&scy;&tcy;4` - CommonMark auto converts it to symbols, so it becomes as "тест4" instead of source with html entities like "&tcy;&iecy;&scy;&tcy;4".

Here http://commonmark.org/help/ is nothing info about HTML entities and `&` symbols. So if this is not a bug, but feature - please describe them in manual.

**Comment by t3chguy** [comment]
I think this is intentional; see Spec http://spec.commonmark.org/0.27/#entity-and-numeric-character-references

**Comment by MurzNN** [comment]
Yes, this is feature, so let's close issue.
