### ISSUE TITLE
The definition of delimiter runs needs more words.

### ISSUE THREAD

**Issue by shyouhei** [jgm/CommonMark#485]
http://spec.commonmark.org/0.27/#delimiter-run says:

> A delimiter run is either a sequence of one or more `*` characters that is not preceded or followed by a `*` character, or a sequence of one or more _ characters that is not preceded or followed by a `_` character.

However we have [example 411](http://spec.commonmark.org/0.27/#example-411):

> ```markdown
> foo *\**
> ```

This is odd.  The last `*` character, which is a right-flanking delimiter run according to the example, is "preceded a `*` character".  This should not be a delimiter run according to the definition.

I think the example shows the intention; the definition of delimiter runs shall be re-thought.

**Comment by aidantwoods** [comment]
We do have rule 11. and 12. which clarify the intent even more.

> 11. A literal `*` character cannot occur at the beginning or end of `*`-delimited emphasis or `**`-delimited strong emphasis, unless it is backslash-escaped.
>
> 12. A literal `_` character cannot occur at the beginning or end of `_`-delimited emphasis or `__`-delimited strong emphasis, unless it is backslash-escaped.

But I think you're right – since it isn't clear that the leading and trailing `*` characters could be considered for a delimiter run from the definition IMO.
