### ISSUE TITLE
custom HtmlRenderer for stmd.js

### ISSUE THREAD

**Issue by rsaccon** [jgm/CommonMark#59]
this is more a feature request than an  issue. Marked has a very slick way to define custom Renderer. From quickly inspecting the code, with stmd.js it is not too difficult, but at best there  is still lots of boilerplate code to be copied into a custom HtmlRenderer and at worst (shame on me, I haven't tried yet), the original HtmlRenderer uses unexported stuff from stmd.js and that would require to patch (or fork) the whole stmd.js

**Comment by jgm** [comment]
Closing here, see jgm/commonmark.js#6.
