### ISSUE TITLE
HTML comments

### ISSUE THREAD

**Issue by dikmax** [jgm/CommonMark#96]
Spec says that HTML Block can begin with html comment. Later it describes html comment:

> An HTML comment consists of the string `<!--`, a string of characters not including the string `--`, and the string `-->`.

So this should be single html block because there's only one html comment:

    

stmd produces (babelmark version):

~~~~~
<!-- 
<p><em>test</em></p>
<p>--&gt;</p>
~~~~~

I think either stmd or spec should be fixed.

**Comment by jgm** [comment]
Closing this, folding the issue into a larger issue #177.
